# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eventos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Eventos
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Toast-Swift', '~> 5.0.1'

  target 'EventosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventosUITests' do
    # Pods for testing
  end

end
